# Generated by Django 5.0.6 on 2024-06-27 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('salary', models.IntegerField()),
                ('description', models.TextField()),
                ('skills', models.TextField()),
                ('experience', models.CharField(max_length=50)),
                ('work_format', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=50)),
                ('employer', models.CharField(max_length=100)),
            ],
        ),
    ]
