# Generated by Django 5.0.6 on 2024-07-01 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_job_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='url',
            field=models.URLField(default=1, unique=True),
        ),
    ]
