# Generated by Django 5.0.6 on 2024-07-03 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_job_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='url',
        ),
    ]
